name = "MetaUtils"
uuid = "ed17dc9e-20eb-4460-9701-8d0520e45e1f"
authors = ["genkuroki <genkuroki@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
AbstractTrees = "0.3"
Revise = "3.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
